---
title: "Cronograma"
author: "Jonas Coelho"
date: "04/11/2021"
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float:
      collapsed: no
    number_sections: yes
    df_print: paged
    code_folding: hide
    self_contained: false
  word_document:
    toc: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{css, echo=FALSE}
pre:not(.r) {
  color: #b0b0b0;
}
```


Carregando bibliotecas
```{r}
library(dplyr)
library(ggplot2)
library(knitr)
library(kableExtra)
options(scipen = 9999)
load('../dados/cronograma.rdata')
load('../dados/novo_cronograma.rdata')
load('../dados/novo_cronograma2.rdata')
```


# Dados 2021


## Rede municipal 2

```{r, results='asis'}
graf <- novo_cronograma2 %>%
  mutate(Híbrido = as.numeric(Híbrido),
         Presencial = as.numeric(Presencial)) %>% filter(rede == 'Municipal') %>%
  select(!rede) %>%
  googleVis::gvisBarChart(
    xvar = 'capital',
    options = list(
      bars = 'horizontal',
      isStacked = TRUE,
      height = 700,
      focusTarget = 'category',
      colors = "['#527184', '#62b5ea', '#f6a323']",
      fontName = 'Source Sans Pro',
      fontSize = 14.4,
      chartArea = "{height:\"90%\"}"
    )
  )


print(graf, "chart")
```

## Rede estadual 2

```{r, results='asis'}
graf <- novo_cronograma2 %>%
  mutate(Híbrido = as.numeric(Híbrido),
         Presencial = as.numeric(Presencial)) %>% filter(rede == 'Estadual') %>%
  select(!rede) %>%
  googleVis::gvisBarChart(
    xvar = 'capital',
    options = list(
      bars = 'horizontal',
      isStacked = TRUE,
      height = 1080,
      focusTarget = 'category',
      colors = "['#527184', '#62b5ea', '#f6a323']",
      fontName = 'Source Sans Pro',
      fontSize = 14.4,
      chartArea = "{height:\"90%\"}"
    )
  )

print(graf, "chart")
```

